/****** errors.c ******/

/*
	$VER: errors.c 0.16A (06.13.2015)

	Error messages.
*/

#include <stdio.h>
#include <stddef.h>
#include "common.h"
#include "errors.h"

static const char *const m_Message[] = {
/* ---- Beginning of error message definitions generated by errors.bas on 05-07-2021 at 14:20:23 ---- */
	NULL,
	"file error",
	"file locked",
	"nonexistent file",
	"file is protected from access",
	"device error",
	"attempt to read past end of file",
	"file size not multiple of record size",
	"record number too large or negative",
	"bad data format",
	"not all files in directory were visited",
	"value outside operator or function domain (possibly missing default clause)",
	"illegal array dimension",
	"out of heap space",
	"numerical overflow",
	"illegal substring",
	"string is empty",
	"division by zero",
	"illegal exponent",
	"subscript out of bounds",
	"bad file number",
	"bad buffer size",
	"file number in use",
	"bad file mode",
	"bad field",
	"out of DATA",
	"bad screen number, or already in use",
	"screen has window(s) open",
	"unable to open screen - is the mode available?",
	"bad window number, or already in use",
	"bad size",
	"couldn't open window",
	"no output window",
	"AREA is too large or has not been defined",
	"statement or function can only be used in --unsafe mode",
	"failed to open audio channel",
	"audio channel denied",
	"failed to allocate memory for waveform",
	"bad sound or waveform parameter",
	"bad menu name",
	"nonexistent menu",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	"internal error",
	"bad command-line arguments",
	"can't open program file",
	"can't open profile output",
	"unimplemented feature",
	"illegal literal",
	"illegal name",
	"line too long",
	"can't redefine existing variable, function, subprogram, or label",
	"undefined subprogram",
	"undefined label",
	"undefined variable or function",
	"syntax error (mismatched parentheses)",
	"syntax error",
	"bad argument or operand count",
	"argument or operand type mismatch",
	"array dimension mismatch",
	"attempt to redimension array",
	"assignment to constant",
	"type mismatch - a scalar is required",
	"type mismatch - an array is required",
	"handler must not have arguments",
	"SUB without ENDSUB",
	"ENDSUB or EXITSUB without SUB",
	"nested SUB or DEF",
	"SHARED outside subprogram",
	"LOCAL outside subprogram",
	"IF without ENDIF",
	"ELSE or ELSEIF without IF",
	"ENDIF without IF",
	"WHILE without WEND",
	"WEND without WHILE",
	"FOR without NEXT",
	"NEXT without FOR",
	"REPEAT without UNTIL or FOREVER",
	"UNTIL or FOREVER without REPEAT",
	"SELECT without ENDSELECT",
	"CASE or OTHERWISE outside a SELECT block",
	"OTHERWISE not last clause in SELECT block",
	"two OTHERWISE clauses in SELECT block",
	"ENDSELECT without SELECT",
	"RETURN without GOSUB",
	"no event to RESUME after",
	"attempt to RESUME into handler",
	"execution halted by signal break (Ctrl-C)",
	"program too large for buffer",
	"function return value doesn't have declared type",
	"Boolean value required",
	"attempt to FORGET inside event handler",
	"module search path(s) too long",
	"stack overflow",
	"stack underflow",
	"unknown event type",
	"a variable is expected here",
	"END statement executed (you shouldn't see this message!)",
	"too many syntax errors - stopping syntax check",
	"bad argument or operand count - parameter is required",
	"NEXT variable doesn't match FOR",
	"attempt to erase argument or shared array in subprogram",
	"too many interpreter instances",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	"event error",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	"internal error",
	"unknown error",
/* ---- End of error message definitions generated by errors.bas on 05-07-2021 at 14:20:23 ---- */
};

/* These must be kept in sync with errors.bas - */
#define MIN_INTERNAL_CODE 200
#define MAX_ERROR_CODE 255

static const char *ErrorMessage(Error errNum)
{
	unsigned code = ErrorCode(errNum);

	if(code == 0 || code > MAX_ERROR_CODE || m_Message[code] == NULL)
		code = MAX_ERROR_CODE; /* i.e. substitute 'unknown error' */
#ifndef DEBUG
	else if(code >= MIN_INTERNAL_CODE)
		code = MAX_ERROR_CODE - 1; /* i.e. substitute generic 'internal error' */
#endif

	return m_Message[code];
}

void ReportError(Error errNumber, const char *file, int line, const char *stmt, char *supplementaryMsg)
{
	unsigned code = ErrorCode(errNumber);
	int obj1Offset = HasErrorObj1(errNumber) ? ErrorObj1Offset(errNumber) : -1;
	int obj2Offset = HasErrorObj2(errNumber) ? ErrorObj2Offset(errNumber) : -1;

	/* TODO get name interpreter was run with */
	fprintf(stderr, "nb: error %u", code);

	/* Print the error location. */
	if(line != -1) {
		if(obj1Offset != -1 && obj2Offset != -1)
			fprintf(stderr, " in %s line %d (symbols at columns %d and %d)", 
				file, line, obj1Offset, obj2Offset);
		else if(obj1Offset != -1)
			fprintf(stderr, " in %s line %d, column %d", 
				file, line, obj1Offset);
		else
			fprintf(stderr, " in %s line %d", file, line);
	}
	else if(file != NULL && file[0] != NUL)
		fprintf(stderr, " in %s line <<unknown>>", file);
    
	/* Print the main error message: */
	fprintf(stderr, ": %s.\n", ErrorMessage(errNumber));

	/* Print any additional message giving context etc.: */
	if(supplementaryMsg != NULL && supplementaryMsg[0] != NUL) {
		fprintf(stderr, "%s\n", supplementaryMsg);
		supplementaryMsg[0] = NUL;
	}

	/* Print the problematic line of code: */
	if(file != NULL && file[0] != NUL && line > 0) {
		while(stmt != NULL && *stmt != '\n' && *stmt != NUL)
			fputc(*stmt++, stderr);
		fputc('\n', stderr);
	}
}

Error PositionError(Error baseError, const char *stmtStart, const char *obj)
{
	ptrdiff_t offset = obj - stmtStart + 1;
	return baseError != SUCCESS && offset > 0 && offset <= MAX_ERROR_OFFSET
		? OneObjError(baseError, offset) : baseError;
}
